<form method="post" action="index.php">
    
    <fieldset>
        <label for="loginEmail">Login</label>
        <input type="email" name="loginEmail" id="loginEmail" />
    </fieldset>
    
    <fieldset>
        <label for="loginPassword">Password</label>
        <input type="password" name="loginPassword" id="loginPassword" />
    </fieldset>
    
    <fieldset>
        <label for="formName">Form Name</label>
        <input type="hidden" name="formName" id="formName" />
    </fieldset>
    
    <input type="submit" value="Connexion"/>
</form>
