<form method="post" action="index.php">
    
    <fieldset>
        <label for="firstName">First Name</label>
        <input type="text" name="firstName" id="firstName" />
    </fieldset>
    
    <fieldset>
        <label for="lastName">Last Name</label>
        <input type="text" name="lastName" id="lastName" />
    </fieldset>
    
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" />
    </fieldset>
    
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" />
    </fieldset>
    
    <fieldset>
        <label for="confirmPassword">Confirm Password</label>
        <input type="password" name="confirmPassword" id="confirmPassword" />
    </fieldset>
    
    <fieldset>
        <label for="formName">formName</label>
        <input type="hidden" name="formName" id="formName" />
    </fieldset>
    
    <input type="submit" value="Création du compte"/>
</form>